version: '3.8'

services:
  vue-app:
    build:
      context: ..  
      dockerfile: docker/Dockerfile  
    ports:
      - "3000:80"
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}
    volumes:
      - ..:/app  # Монтируем родительский каталог в контейнер
    command: ["npm", "run", "dev"]   